version: "3.7"

services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=teste
      - POSTGRES_PASSWORD=teste123
      - POSTGRES_DB=teste
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres: